version: '3.4'
services:

  duckling-server:
    image: rasa/duckling:latest
    ports:
    - 8000:8000
    networks:
    - all

  rasa:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --debug"
    ports:
      - '5006:5005'
    public: true
    networks:
      - all

  rasa-actions:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
      - ./actions:/app/actions
      - ./utils:/app/utils
    command: ["rasa", "run", "actions"]
    ports:
      - '5055:5055'
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.networks.enabled: "true"
